azure:
  free_disk_space: true
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
  # These timeout settings are set to avoid a rebuild of
  # build 24 for osx and windows
  # since build 24 was triggered in order to address the
  # inability to download build 23 on linux-64
  # https://github.com/conda-forge/qt-main-feedstock/issues/280
    timeoutInMinutes: 1
  settings_osx:
    timeoutInMinutes: 1
bot:
  abi_migration_branches:
  - qt6
build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: default
  linux_ppc64le: default
remote_ci_setup:
- liblief=0.11.5
- conda-forge-ci-setup=3
test: native_and_emulated
