azure:
  free_disk_space: true
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
      MINIFORGE_HOME: C:\Miniforge
bot:
  abi_migration_branches:
  - qt6
  - 'qt5.15.8'
build_platform:
  linux_aarch64: linux_aarch64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux: github_actions
  linux_aarch64: default
test: native_and_emulated
